sudo: required
services:
  - docker

before_install:
  - docker build -t umbrellacorpagent/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true umbrellacorpagent/docker-react npm run test -- --coverage 