sudo: required
services:
  - docker

before_install:
  - docker build -t umbrellacorpagent/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true umbrellacorpagent/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ca-central-1-532651301647"
  bucket_path: "docker-react"
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY